### ISSUE TITLE
Unable to run app using node.js 10

### ISSUE THREAD

**Issue by rgf1042** [rgf1042/fibairfy-server#3]
When using this app in node.js runtime version 10 it throws the next error:

error: Failed to lift app: Error: Attempted to `require('/home/roger/dev/rgfnet/fibairfy-server/api/controllers/InputOutputController.js')`, but an error occurred:

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/home/roger/dev/rgfnet/fibairfy-server/node_modules/natives/index.js:137:5)
    at require (/home/roger/dev/rgfnet/fibairfy-server/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/home/roger/dev/rgfnet/fibairfy-server/node_modules/natives/index.js:137:5)
    at require (/home/roger/dev/rgfnet/fibairfy-server/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/home/roger/dev/rgfnet/fibairfy-server/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/home/roger/dev/rgfnet/fibairfy-server/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/home/roger/dev/rgfnet/fibairfy-server/node_modules/unzip/node_modules/graceful-fs/fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/roger/dev/rgfnet/fibairfy-server/node_modules/unzip/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)

    at /home/roger/dev/rgfnet/fibairfy-server/node_modules/include-all/lib/help-include-all-sync.js:298:25
    at Array.forEach (<anonymous>)
    at _recursivelyIncludeAll (/home/roger/dev/rgfnet/fibairfy-server/node_modules/include-all/lib/help-include-all-sync.js:178:11)
    at includeAll (/home/roger/dev/rgfnet/fibairfy-server/node_modules/include-all/lib/help-include-all-sync.js:317:5)
    at helpBuildDictionary (/home/roger/dev/rgfnet/fibairfy-server/node_modules/include-all/lib/help-build-dictionary.js:46:13)
    at Function.module.exports.optional (/home/roger/dev/rgfnet/fibairfy-server/node_modules/include-all/index.js:67:10)
    at loadActionModules (/home/roger/dev/rgfnet/fibairfy-server/node_modules/sails/lib/app/private/controller/load-action-modules.js:27:14)
    at async.auto.controller (/home/roger/dev/rgfnet/fibairfy-server/node_modules/sails/lib/app/load.js:101:9)
    at runTask (/home/roger/dev/rgfnet/fibairfy-server/node_modules/sails/node_modules/async/dist/async.js:1619:13)
    at /home/roger/dev/rgfnet/fibairfy-server/node_modules/sails/node_modules/async/dist/async.js:1559:13
    at processQueue (/home/roger/dev/rgfnet/fibairfy-server/node_modules/sails/node_modules/async/dist/async.js:1569:13)
    at taskComplete (/home/roger/dev/rgfnet/fibairfy-server/node_modules/sails/node_modules/async/dist/async.js:1588:9)
    at /home/roger/dev/rgfnet/fibairfy-server/node_modules/sails/node_modules/async/dist/async.js:1612:17
    at /home/roger/dev/rgfnet/fibairfy-server/node_modules/sails/node_modules/async/dist/async.js:906:16
    at /home/roger/dev/rgfnet/fibairfy-server/node_modules/sails/lib/app/load.js:191:14
    at /home/roger/dev/rgfnet/fibairfy-server/node_modules/sails/node_modules/async/dist/async.js:3861:9
    at /home/roger/dev/rgfnet/fibairfy-server/node_modules/sails/node_modules/async/dist/async.js:421:16
    at replenish (/home/roger/dev/rgfnet/fibairfy-server/node_modules/sails/node_modules/async/dist/async.js:941:25)
    at iterateeCallback (/home/roger/dev/rgfnet/fibairfy-server/node_modules/sails/node_modules/async/dist/async.js:931:17)
    at /home/roger/dev/rgfnet/fibairfy-server/node_modules/sails/node_modules/async/dist/async.js:906:16
    at /home/roger/dev/rgfnet/fibairfy-server/node_modules/sails/node_modules/async/dist/async.js:3858:13
    at afterwards (/home/roger/dev/rgfnet/fibairfy-server/node_modules/sails/lib/app/private/loadHooks.js:351:16)

**Comment by rgf1042** [comment]
The problem is in unzip package. We should try to change it to a more "updated" package.

**Comment by rgf1042** [comment]
Fixed in 9102894832c9addc52a12df64647782b248092b3.
